### ISSUE TITLE
Products -> Selling unit // selling_unit of type ?float

### ISSUE THREAD

**Issue by Timba90** [Team-Nifty-GmbH/flux-core#314]
Cannot assign string to property FluxErp\Livewire\Forms\ProductForm::$selling_unit of type ?float

![image](https://github.com/Team-Nifty-GmbH/flux-core/assets/61355532/b0ad60a6-1148-4ea5-a753-22694da4ea67)

**Comment by Timba90** [comment]
Falsch verstanden.
Dann fehlt mir ein Feld: Pro Stück, Pauschal

**Comment by patrickweh** [comment]
https://github.com/Team-Nifty-GmbH/flux-core/pull/586

Should solve this
